'use client';
import { useState } from 'react';
import { FaCircleCheck, FaPaperPlane } from 'react-icons/fa6';
import Navbar from '@/components/Navbar'; import Footer from '@/components/Footer'; import { BackToTop, CustomCursor } from '@/components/UI';
export default function OpportunityPage({ eyebrow, title, emphasis, intro, benefits, topic }: { eyebrow:string; title:string; emphasis:string; intro:string; benefits:string[]; topic:string }) {
 const [form,setForm]=useState({name:'',email:'',message:''}); const [sent,setSent]=useState(false); const [sending,setSending]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setSending(true);try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,budget:topic,message:`[${topic}] ${form.message}`})});if(!r.ok)throw Error();setSent(true)}finally{setSending(false)}}
 return <><CustomCursor/><Navbar/><main className="cursor-none min-h-screen pt-32 pb-20"><div className="max-w-5xl mx-auto px-6 lg:px-8 grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><section><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#F97316]">{eyebrow}</p><h1 className="mt-5 text-4xl md:text-5xl font-bold leading-tight text-white">{title} <span className="text-[#F97316]">{emphasis}</span></h1><p className="mt-6 leading-relaxed text-[#888]">{intro}</p><div className="mt-8 rounded-2xl border border-[#222] bg-[#111] p-6"><p className="text-xs uppercase tracking-widest text-[#555]">What you can expect</p><ul className="mt-5 space-y-3">{benefits.map(item=><li key={item} className="text-sm leading-relaxed text-[#AAA]">• {item}</li>)}</ul></div></section><section className="rounded-2xl border border-[#222] bg-[#111] p-6 md:p-8">{sent?<div className="flex min-h-[360px] flex-col items-center justify-center text-center"><FaCircleCheck size={50} className="mb-5 text-[#F97316]"/><h2 className="text-2xl font-bold text-white">Submission received.</h2><p className="mt-3 max-w-sm text-[#777]">It is now in the portfolio message queue and will be reviewed privately.</p></div>:<form onSubmit={submit} className="space-y-5"><p className="text-sm text-[#777]">Use this dedicated form—your request is recorded in the dashboard, not sent through a public direct link.</p><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name" className="w-full rounded-xl border border-[#242424] bg-[#0D0D0D] px-4 py-3 text-sm text-white"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Work email" className="w-full rounded-xl border border-[#242424] bg-[#0D0D0D] px-4 py-3 text-sm text-white"/><textarea required rows={7} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Share the relevant details..." className="w-full resize-none rounded-xl border border-[#242424] bg-[#0D0D0D] px-4 py-3 text-sm text-white"/><button disabled={sending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#F97316] py-3.5 text-sm font-semibold text-white disabled:opacity-60"><FaPaperPlane size={13}/>{sending?'Saving...':'Submit privately'}</button></form>}</section></div></main><Footer/><BackToTop/></>;
}
