'use client';
import { useEffect, useState } from 'react';
import { FaFloppyDisk, FaPlus, FaSpinner, FaTrash } from 'react-icons/fa6';
import toast from 'react-hot-toast';
import ImageUpload from '@/components/admin/ImageUpload';

type Item = { title: string; description?: string; url?: string; imageUrl?: string; imageId?: string };
const sections = [{ key: 'more_links', label: 'Links', images: false }, { key: 'more_uses', label: 'Uses', images: false }, { key: 'more_gallery', label: 'Gallery', images: true }, { key: 'more_bucket_list', label: 'Bucket List', images: true }] as const;
export default function AdminMore() {
  const [content, setContent] = useState<Record<string, Item[]>>({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/more').then(r => r.json()).then(r => setContent(r.data ?? {})).finally(() => setLoading(false)); }, []);
  const update = (key: string, index: number, update: Partial<Item>) => setContent(old => ({ ...old, [key]: (old[key] ?? []).map((item, i) => i === index ? { ...item, ...update } : item) }));
  const add = (key: string) => setContent(old => ({ ...old, [key]: [...(old[key] ?? []), { title: '', description: '', url: '' }] }));
  const remove = (key: string, index: number) => setContent(old => ({ ...old, [key]: old[key].filter((_, i) => i !== index) }));
  async function save() { setSaving(true); try { const r = await fetch('/api/more', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(content) }); if (!r.ok) throw new Error(); toast.success('More content saved'); } catch { toast.error('Could not save content'); } finally { setSaving(false); } }
  if (loading) return <div className="flex justify-center py-24"><FaSpinner className="animate-spin text-[#F97316]" /></div>;
  return <div className="max-w-3xl p-6 pt-20 md:p-8 md:pt-8"><div className="mb-8 flex items-center justify-between"><div><h1 className="text-2xl font-bold text-white">More content</h1><p className="mt-1 text-sm text-[#555]">Manage the public Links, Uses, Gallery, and Bucket List pages.</p></div><button onClick={save} disabled={saving} className="flex items-center gap-2 rounded-xl bg-[#F97316] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? <FaSpinner className="animate-spin" /> : <FaFloppyDisk />} Save</button></div><div className="space-y-7">{sections.map(section => <section key={section.key} className="rounded-2xl border border-[#1E1E1E] bg-[#111] p-5"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold text-white">{section.label}</h2><button onClick={() => add(section.key)} className="flex items-center gap-1.5 text-sm text-[#F97316]"><FaPlus size={12}/> Add item</button></div><div className="space-y-4">{(content[section.key] ?? []).map((item, index) => <div key={index} className="rounded-xl border border-[#222] bg-[#0D0D0D] p-4"><div className="mb-3 flex justify-end"><button onClick={() => remove(section.key, index)} className="text-[#666] hover:text-red-400"><FaTrash size={13}/></button></div><div className="grid gap-3 sm:grid-cols-2"><input value={item.title} onChange={e => update(section.key,index,{title:e.target.value})} placeholder="Title" className="rounded-lg border border-[#242424] bg-[#111] px-3 py-2 text-sm text-white"/><input value={item.url ?? ''} onChange={e => update(section.key,index,{url:e.target.value})} placeholder="Optional URL" className="rounded-lg border border-[#242424] bg-[#111] px-3 py-2 text-sm text-white"/></div><textarea value={item.description ?? ''} onChange={e => update(section.key,index,{description:e.target.value})} placeholder="Description" rows={2} className="mt-3 w-full rounded-lg border border-[#242424] bg-[#111] px-3 py-2 text-sm text-white"/>{section.images && <div className="mt-3"><ImageUpload value={item.imageUrl} publicId={item.imageId} folder="more" label="Image" onUpload={(imageUrl,imageId) => update(section.key,index,{imageUrl,imageId})} onRemove={() => update(section.key,index,{imageUrl:'',imageId:''})}/></div>}</div>)}{!(content[section.key] ?? []).length && <p className="py-4 text-sm text-[#555]">No items yet.</p>}</div></section>)}</div></div>;
}
